name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deployment
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: forever stopall
    - run: rm ./o.log ./e.log
      continue-on-error: true
    - run: forever start -o ./o.log -e ./e.log src/app.js
